// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var form, textarea;
    textarea = $('.materialize-textarea');
    textarea.val('New Text');
    textarea.trigger('autoresize');
    form = $('form');
    return form.validate({
      errorClass: 'invalid',
      errorPlacement: function(error, element) {
        return element.next("label").attr("data-error", error.contents().text());
      }
    });
  })(jQuery);

}).call(this);

//# sourceMappingURL=contact.js.map
