// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var textarea;
    textarea = $('.materialize-textarea');
    textarea.val('New Text');
    return textarea.trigger('autoresize');
  })(jQuery);

}).call(this);

//# sourceMappingURL=contact.js.map
