// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var form, textarea;
    textarea = $('.materialize-textarea');
    textarea.trigger('autoresize');
    return form = $('form');
  })(jQuery);

}).call(this);

//# sourceMappingURL=contact.js.map
